apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-nginx-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/raksha-shenoy/demo-nginx.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: demo-nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true